# Generated by Django 4.2 on 2026-03-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailyanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('combo_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_addons', to='api.menuitem')),
                ('main_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_combos', to='api.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='api.restaurant')),
            ],
            options={
                'db_table': 'combos',
                'unique_together': {('restaurant', 'main_item', 'combo_item')},
            },
        ),
    ]
