# Generated by Django 4.2 on 2026-03-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_rating_order_review_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discount_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
