# Generated by Django 4.2 on 2026-03-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_menuitem_discount_price_menuitem_discount_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='state',
            field=models.CharField(choices=[('Solids', 'Solids'), ('Liquids', 'Liquids'), ('Semi-Solid', 'Semi-Solid')], default='Solids', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(choices=[('Sweet', 'Sweet'), ('Very Sweet', 'Very Sweet'), ('Mild', 'Mild'), ('Medium', 'Medium'), ('Hot', 'Hot'), ('Extra Hot', 'Extra Hot')], default='Medium', max_length=20),
        ),
    ]
