# Generated by Django 4.2 on 2026-03-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_menuitem_state_alter_menuitem_spice_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'New Order'), ('item_created', 'Item Created'), ('combo_created', 'Combo Created'), ('price_updated', 'Price Updated'), ('promotion_applied', 'Promotion Applied')], max_length=30)),
                ('icon', models.CharField(default='🔔', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.restaurant')),
            ],
            options={
                'db_table': 'owner_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
