# Generated by Django 4.2 on 2026-03-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ownernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownernotification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('item_created', 'Item Created'), ('combo_created', 'Combo Created'), ('price_updated', 'Price Updated'), ('promotion_applied', 'Promotion Applied'), ('order_status_update', 'Order Status Update'), ('daily_sales_summary', 'Daily Sales Summary')], max_length=30),
        ),
        migrations.CreateModel(
            name='OwnerNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_order_alerts', models.BooleanField(default=True)),
                ('order_status_updates', models.BooleanField(default=True)),
                ('daily_sales_summary', models.BooleanField(default=True)),
                ('ai_suggestions', models.BooleanField(default=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='api.restaurant')),
            ],
            options={
                'db_table': 'owner_notification_settings',
            },
        ),
    ]
