# Generated by Django 4.2 on 2026-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_ownernotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price_optimized_count',
            field=models.IntegerField(default=0),
        ),
    ]
